<a href="https://colab.research.google.com/github/shibataryoma22-hub/-udemy/blob/main/basic_pandas_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DataFrameの作成
DataFrameはラベル付きの二次元配列で、整数や少数、文字列などさまざまな型のデータを格納することができる

In [4]:
import pandas as pd
import numpy as np

In [6]:
a = pd.DataFrame([[80, 60, 70, True],
                  [90, 80, 70, True],
                  [70, 60 ,50, True],
                  [40, 60, 50, False],
                  [20, 30, 40, False],
                  [50, 20, 10, False]])

In [7]:
print(a)

    0   1   2      3
0  80  60  70   True
1  90  80  70   True
2  70  60  50   True
3  40  60  50  False
4  20  30  40  False
5  50  20  10  False

In [10]:
a.index = ["1", "2", "3", "4", "5", "6"]
a.columns = ["Japanese", "Math", "English", "Result"]
print(a)

   Japanese  Math  English  Result
1        80    60       70    True
2        90    80       70    True
3        70    60       50    True
4        40    60       50   False
5        20    30       40   False
6        50    20       10   False

In [12]:
a.shape #行列

(6, 4)

In [14]:
a.head() #最初の５行

   Japanese  Math  English  Result
1        80    60       70    True
2        90    80       70    True
3        70    60       50    True
4        40    60       50   False
5        20    30       40   False

In [15]:
a.tail() #最後の５行

   Japanese  Math  English  Result
2        90    80       70    True
3        70    60       50    True
4        40    60       50   False
5        20    30       40   False
6        50    20       10   False

In [16]:
a.describe() #基本的な統計量

        Japanese       Math    English
count   6.000000   6.000000   6.000000
mean   58.333333  51.666667  48.333333
std    26.394444  22.286020  22.286020
min    20.000000  20.000000  10.000000
25%    42.500000  37.500000  42.500000
50%    60.000000  60.000000  50.000000
75%    77.500000  60.000000  65.000000
max    90.000000  80.000000  70.000000

In [18]:
#DataFrameの操作
tr = a.loc["1", :] #１行取り出す
print(type(tr))
tr

<class 'pandas.core.series.Series'>

Japanese      80
Math          60
English       70
Result      True
Name: 1, dtype: object

In [19]:
ma = a.loc[:, "English"]
print(type(ma))
ma

<class 'pandas.core.series.Series'>

1    70
2    70
3    50
4    50
5    40
6    10
Name: English, dtype: int64

In [20]:
#ilocによって範囲指定可能になる
r = a.iloc[1:4, :2] #1行目から３行目まで、０－１列
print(type(r))
r

<class 'pandas.core.frame.DataFrame'>

   Japanese  Math
2        90    80
3        70    60
4        40    60

In [21]:
#locメソッドによる行の追加
a.loc["Shiro"] = pd.Series([70, 80, 70, True], index = ["Japanese", "Math", "English", "Result"], name = "Shiro")

In [22]:
print(a)

       Japanese  Math  English  Result
1            80    60       70    True
2            90    80       70    True
3            70    60       50    True
4            40    60       50   False
5            20    30       40   False
6            50    20       10   False
Shiro        70    80       70    True

In [24]:
#列ラベルの指定で列を追加できる
a["Science"] = [80, 70, 60, 50, 60, 40, 80]
a

       Japanese  Math  English  Result  Science
1            80    60       70    True       80
2            90    80       70    True       70
3            70    60       50    True       60
4            40    60       50   False       50
5            20    30       40   False       60
6            50    20       10   False       40
Shiro        70    80       70    True       80

In [25]:
a.sort_values(by="Math", ascending=False)

       Japanese  Math  English  Result  Science
2            90    80       70    True       70
Shiro        70    80       70    True       80
1            80    60       70    True       80
3            70    60       50    True       60
4            40    60       50   False       50
5            20    30       40   False       60
6            50    20       10   False       40